graph = TinkerGraph.open()
g = graph.traversal(standard())
daenerys = graph.addVertex(label,'human','name','Daenerys','house','Targaryen','origin','Dragonstone')
viserys = graph.addVertex(label,'human','name','Viserys','house','Targaryen','origin','King\'s Landing')
drogon = graph.addVertex(label,'dragon','name','Drogon','colors','black and red')
viserion = graph.addVertex(label,'dragon','name','Viserion','colors','gold and red-orange')
rhaegal = graph.addVertex(label,'dragon','name','Rhaegal','colors','green bronze and yellow-orange')
daenerys.addEdge('relatedBy',viserys).property('relationship','sister')
viserys.addEdge('relatedBy',daenerys).property('relationship','brother')
daenerys.addEdge('hatchedBy',drogon)
daenerys.addEdge('hatchedBy',viserion)
daenerys.addEdge('hatchedBy',rhaegal)
