schema.propertyKey("ISBN").Text().single().create()
schema.propertyKey("gender").Text().single().create()
schema.propertyKey("year").Text().single().create()
schema.propertyKey("name").Text().single().create()
schema.edgeLabel("authored").multiple().create()
schema.vertexLabel("author").properties("name", "gender").create()
schema.vertexLabel("author").index("byname").materialized().by("name").add()
schema.vertexLabel("book").properties("ISBN", "year", "name").create()
schema.vertexLabel("book").index("byname").materialized().by("name").add()
schema.edgeLabel("authored").connection("author", "book").add()
