// TRAVERSAL EXAMPLES

// How many recipes exist in the database?
g.V().count()

// How many recipes has Julia Child written?

// Which recipes list beef as an ingredient?

// Which recipes list beef and mashed garlic as ingredients?

// Which cookbooks list Julia Child as an author?

// Which cookbooks were published in 1980?

// How many reviewers have reviewed Beef Bourguignon?

// What did a particular reviewer say about Beef Bourguignon?

// What reviewers rated Beef Bourguignon in the last 15 days?

// Which reviewers who rated Beef Bourguignon with 5 stars rated other recipes?

// What other recipes did reviewers who rated Beef Bourguignon with 5 stars also rate with 5 stars?

// What cookbooks have recipes that list beef and mashed garlic as ingredients?

// What are the recipes included in the cookbooks that list beef and mashed garlic as ingredients?

--------------
// Which meals list Beef Bourguignon as an item?

// Which meals have a calorie count of 1,100 calories or less? 

-----------
BRANCHING TRAVERSAL:
// If the vertex selected is an author, then count the number of outgoing edges "created"; else if the vertex selected is a reviewer, then count the number of outgoing
edges "rated"; otherwise, do nothing.
g.V().choose(label()).
 option("author", out("created").count()).
 option("reviewer", out("rated").count()).
 option(none, label())

------------
RECURSIVE TRAVERSAL:
// Return the names of the vertices 2 outgoing steps from the vertex named "Julia Child". This will likely include cookbooks, meals, reviewers, and ingredients.
g.V().has('name','Julia Child').
 repeat(out()).times(2).
 values('name')

-------
PATH TRAVERSAL:

g.V().as("a").out().as("b","c").path()

-----------
PROJECTING TRAVERSAL:

g.V().as("a").out("knows").as("b").
select("a","b").
by(in("knows").count()).
by(out("knows").count())


